### ISSUE TITLE
To-Do 리스트

### ISSUE THREAD

**Issue by WTPENGUIN** [the-peach-drone/fastapi-flight-record-server#1]
TODO List : 
- [ ] View record - 기록 view 프론트엔드 페이지
- [ ] 로그 통합 - Loguru 로깅과 uvicorn 로깅 통합
- [x] Request routing result - 다른 API 서버로 보낼 때, 응답 메세지 로깅
- [x] Config - Config 파일로 연결 정보 export
- [ ] Startup Env - Docker 환경에서 실행하거나 따로 Startup 스크립트 작성
- [ ] API 다중 호출 테스트 - 여러 Host에서 해당 API 호출 테스트
- [x] Server Function - HTTP POST로 파일 받기
- [x] Server Function - 응답 JSON 바디 제작 
- [x] Server Init - 기초 init 코드 구현(테이블 없을 시 테이블 생성, 저장 폴더 없을 시 저장 폴더 생성)
- [x] Server Function - CSV 및 JSON 따로 저장
- [x] Server Logging - 기초 로깅 적용
- [x] DB - Cache 기능 적용
- [x] Server Logging - 항목별로 로깅 색깔 다르게 적용
- [x] Server Logging - 파일로 서버 로그 저장
- [x] DB - 쿼리 실행 코드 정리
- [x] Config - 서버 Config 기능 추가
- [x] Request Routing - 다른 API 서버로 파일 내용 JSON화 하여 HTTP POST로 전송

**Comment by WTPENGUIN** [comment]
To-Do 리스트 다른 곳에 정리 예정
